GET http://localhost:3001/api/library/movies


###

GET http://localhost:3001/api/library/movies?filter=favorites

###

GET http://localhost:3001/api/library/movies?filter=maxR

###

GET http://localhost:3001/api/library/movies?filter=unseen

###

GET http://localhost:3001/api/library/movies?filter=lastMonth

###

GET http://localhost:3001/api/library/movies/1

###

POST http://localhost:3001/api/library/movies
content-type: application/json

{
  "title": "Avatar",
  "favorites": 0,
  "rating": 5,
  "date": "2024-04-01",
  "userid": 1
}

###


PUT http://localhost:3001/api/library/movies/6
content-type: application/json

{  
  "title": "Interstellar",
  "favorites": 1,
  "rating": 4,
  "date": "2024-04-07",
  "userid": 2
}

